### ISSUE TITLE
Bug in StorableFileFactory.php

### ISSUE THREAD

**Issue by JoshMcCr-roofr** [czim/file-handling#15]
The exception thrown on line 171 has reference to '->getcode' which should be '->getCode'.
This is causing this exception to always throw a code 0

```
throw new CouldNotRetrieveRemoteFileException(
    "Could not retrieve file from '{$url}'",
    $e->getcode(), // bug here
    $e
);
```

**Comment by czim** [comment]
Sloppy on my part, thanks for reporting this.
