### ISSUE TITLE
VideoScreenshotStrategy changes file name

### ISSUE THREAD

**Issue by asdacap** [czim/file-handling#4]
VideoScreenshotStrategy changes file name which it extract from temporary filename. https://github.com/czim/file-handling/blob/f0b9eda6f46125339d69a5c34e4cd40b347ca0ce/src/Variant/Strategies/VideoScreenshotStrategy.php#L18-L20

It set it here:
https://github.com/czim/file-handling/blob/f0b9eda6f46125339d69a5c34e4cd40b347ca0ce/src/Variant/Strategies/VideoScreenshotStrategy.php#L50

This causes breakage in laravel-paperclip which seems to assume all variant have the same name, but may have different extension. So getting the url of the screenshot, something like `$model->video->url('screenshot')` resulting in a url with the original filename which does not exist.

Changing line 20 to something like `$imageName = pathinfo($this->file->name(), PATHINFO_FILENAME) . '.jpg';`. Fixes the issue.

**Comment by czim** [comment]
This issue should be fixed in version `1.0.2`. Can you confirm this?
