### ISSUE TITLE
Unable to read exif data on php 7.2 as required in OrientationFixer

### ISSUE THREAD

**Issue by kyranb** [czim/file-handling#7]
As per these failing tests: https://travis-ci.org/czim/file-handling/jobs/477529848 with the following error: `exif_read_data(tmp.jpg): Process tag(x0131=Software   ): Illegal components(0)`

It seems that as of php 7.2 the `exif_read_data()` function has a bug or is no longer compatible: https://bugs.php.net/bug.php?id=75785

and here is some further discussion here: https://stackoverflow.com/a/50890651

**Comment by czim** [comment]
I've added the `@` prefix for quiet-mode on the fixer, so at least the error spam should be reduced now.
